name: quality check

on:
  push:
    branches:
      - master
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  quality_check:
    name: quality check (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: ${{ matrix.timeout_minutes }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            timeout_minutes: 45
          - os: macos-latest
            timeout_minutes: 60
          - os: windows-latest
            timeout_minutes: 60

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install nightly rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy

      - name: cache cargo artifacts
        uses: Swatinem/rust-cache@v2

      - name: cargo fmt
        run: cargo +nightly fmt --all -- --check

      - name: cargo clippy
        run: cargo +nightly clippy --all-targets --all-features --locked -- -D warnings

      - name: cargo test
        run: cargo +nightly test --all-features --locked
